name: Who Pays Main CI

on:
  push:
    branches:
      - main

jobs:
  static_code_analysys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run spotlessCheck gradle task
        run: ./gradlew spotlessKotlinApply

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        uses: ./gradlew test